In [1]:
import pandas as pd
import numpy as np

values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [2]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [4]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [6]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [7]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [8]:
#--- pandas一个分类模型 ----
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
df = pd.DataFrame({'fruit':fruits,
                   'basket_id':np.arange(N),
                   'count':np.random.randint(3, 15, size=N),
                   'weight':np.random.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  3.304922
1          1  orange      8  3.290029
2          2   apple     10  3.720711
3          3   apple      4  0.701207
4          4   apple     10  1.291443
5          5  orange     14  3.931841
6          6   apple      9  3.932090
7          7   apple      6  1.803500

In [9]:
fruit_cat = df['fruit'].astype('category')

In [10]:
c = fruit_cat.values

In [11]:
type(c)

pandas.core.categorical.Categorical

In [12]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [13]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [14]:
df['fruit'] = df['fruit'].astype('category')

In [16]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [17]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [18]:
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [19]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [20]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [21]:
ordered_cat

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [22]:
my_cats_2.as_ordered()

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [23]:
np.random.seed(123456)
draws = np.random.randn(1000)
draws[:5]

array([ 0.4691123 , -0.28286334, -1.5090585 , -1.13563237,  1.21211203])

In [24]:
bins = pd.qcut(draws, 4)
bins

[(0.0347, 0.641], (-0.797, 0.0347], (-3.522, -0.797], (-3.522, -0.797], (0.641, 3.357], ..., (-3.522, -0.797], (0.641, 3.357], (-0.797, 0.0347], (-0.797, 0.0347], (-3.522, -0.797]]
Length: 1000
Categories (4, interval[float64]): [(-3.522, -0.797] < (-0.797, 0.0347] < (0.0347, 0.641] < (0.641, 3.357]]

In [25]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

[Q3, Q2, Q1, Q1, Q4, ..., Q1, Q4, Q2, Q2, Q1]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [26]:
bins.codes[:10]

array([2, 1, 0, 0, 3, 1, 2, 0, 0, 0], dtype=int8)

In [27]:
bins = pd.Series(bins, name='quartile')

In [28]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())
results

quartile  count       min       max
0       Q1    250 -3.520876 -0.798334
1       Q2    250 -0.796211  0.033113
2       Q3    250  0.036220  0.641385
3       Q4    250  0.641606  3.357427

In [29]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [30]:
N = 10000000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['foo', 'bar','baz','qux'] * (N//4))

In [31]:
categories = labels.astype('category')

In [32]:
labels.memory_usage()

80000080

In [33]:
categories.memory_usage()

10000272

In [34]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [35]:
cat_s = s.astype('category')

In [36]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [37]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [38]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [39]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [40]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [41]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [42]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [43]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

In [44]:
#------ 创建虚拟变量 ----------
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [45]:
df = pd.DataFrame({'key':['a', 'b', 'c'] * 4,
                   'value':np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [46]:
g = df.groupby('key').value

In [47]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [48]:
g.transform(lambda x:x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [49]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [50]:
g.transform(lambda x:x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [51]:
def normalize(x):
    return (x - x.mean())/x.std()
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [52]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [53]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [54]:
normalized = (df['value'] - g.transform('mean'))/g.transform('std')

In [56]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [57]:
#-------- 分组时间采样 -----------
N = 15
times = pd.date_range('2017-05-20 00:00', freq='1min', periods=N)
df = pd.DataFrame({'time':times, 
                   'value':np.arange(N)})
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [59]:
#---- 进行重采样 5min进行一个汇总 -----
df.set_index('time').resample('5min').sum()

value
time                      
2017-05-20 00:00:00     10
2017-05-20 00:05:00     35
2017-05-20 00:10:00     60

In [60]:
df2 = pd.DataFrame({'time':times.repeat(3),
                    'key':np.tile(['a', 'b', 'c'], N),
                    'value':np.arange(N*3.)})
df2[:7]

key                time  value
0   a 2017-05-20 00:00:00    0.0
1   b 2017-05-20 00:00:00    1.0
2   c 2017-05-20 00:00:00    2.0
3   a 2017-05-20 00:01:00    3.0
4   b 2017-05-20 00:01:00    4.0
5   c 2017-05-20 00:01:00    5.0
6   a 2017-05-20 00:02:00    6.0

In [62]:
time_key = pd.TimeGrouper('5min')
resampled = (df2.set_index('time').groupby(['key', time_key]).sum())
resampled

value
key time                      
a   2017-05-20 00:00:00   30.0
    2017-05-20 00:05:00  105.0
    2017-05-20 00:10:00  180.0
b   2017-05-20 00:00:00   35.0
    2017-05-20 00:05:00  110.0
    2017-05-20 00:10:00  185.0
c   2017-05-20 00:00:00   40.0
    2017-05-20 00:05:00  115.0
    2017-05-20 00:10:00  190.0

In [63]:
resampled.reset_index()

key                time  value
0   a 2017-05-20 00:00:00   30.0
1   a 2017-05-20 00:05:00  105.0
2   a 2017-05-20 00:10:00  180.0
3   b 2017-05-20 00:00:00   35.0
4   b 2017-05-20 00:05:00  110.0
5   b 2017-05-20 00:10:00  185.0
6   c 2017-05-20 00:00:00   40.0
7   c 2017-05-20 00:05:00  115.0
8   c 2017-05-20 00:10:00  190.0

In [64]:
result = (df.pipe(f, arg1=v1)
            .pipe(g, v2, arg3=v3)
            .pipe(h, arg4=v4))

NameError: name 'f' is not defined

In [65]:
def group_demean(df, by, cols):
    result = df.copy()
    g = df.groupby(by)
    for c in cols:
        result[c] = df[c] - g[c].transform('mean')
    return result
result = (df[df.col1 < 0].pipe(group_demean, ['key1', 'key2'], ['col1']))

AttributeError: 'DataFrame' object has no attribute 'col1'