### 1.导入numpy库并简写为np

In [1]:
import numpy as np

### 2.打印numpy的版本和配置说明

In [5]:
print (np.__version__)
np.show_config()

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


### 3. 创建一个长度为10的空间量

In [7]:
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. 如何找到任何一个数组的内存大小

In [8]:
mat = np.zeros((5, 5))
print ("{} bytes".format(mat.size * mat.itemsize))

200 bytes


### 5.如何从命令行中得到numpy中的add函数的说明文档?

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6.创建一个长度为10并且除了第五个值为1的空向量

In [12]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 7.创建一个值域范围从10到49的向量

In [15]:
Z = np.arange(10, 50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. 反转一个向量(第一个元素变为最后一个)

In [17]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 9. 创建一个3X3并且值从0到8的矩阵

In [20]:
z = np.arange(9).reshape(3, 3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. 找到数组[1, 2, 0, 0, 4, 0]中非0元素的位置索引

In [22]:
nz_list = [1,2,0,0,4,0]
nz_index = np.nonzero(nz_list)
nz_index

(array([0, 1, 4], dtype=int64),)

### 11.创建一个3x3的单位矩阵

In [24]:
z = np.eye(3, 3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12.创建一个3x3x3的随机数组

In [27]:
z = np.random.random((3, 3, 3))
z

array([[[0.84894519, 0.39147331, 0.25474402],
        [0.74370606, 0.66442117, 0.87794982],
        [0.81918856, 0.48027443, 0.57934425]],

       [[0.48943216, 0.72363489, 0.64044557],
        [0.5032271 , 0.10715467, 0.90807752],
        [0.18197596, 0.06519368, 0.54523407]],

       [[0.39838192, 0.0865473 , 0.84168363],
        [0.54679414, 0.36734537, 0.38528773],
        [0.64158819, 0.70426165, 0.20119188]]])

### 13. 创建一个10x10的随机数组并找到它的最大值最小值

In [29]:
z = np.random.random((10, 10))
zmin, zmax = z.min(), z.max()
print (zmin, zmax)

0.0026387892507346855 0.9880190321400006


### 14.创建一个长度为30的随机向量并找到它的平均值

In [31]:
z = np.random.random(30)
m = z.mean()
print (m)

0.5427694928168987


### 15. 创建一个二维数组,其中边界值为1,其余值为0

In [33]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print (Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16.对于一个存在在数组,如何添加一个用0填充的边界?

In [35]:
z = np.ones((5, 5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### 17.以下表达式运行的结果分别是什么

In [41]:
print (0*np.nan) 
print (np.nan == np.nan)
print (np.inf > np.nan)
print (np.nan - np.nan)
print (0.3 == 3 * 0.1)

False

### 18. 创建一个5X5的矩阵,并设置1,2,3,4落在其对角线下方的位置

In [45]:
z = np.diag(1+np.arange(4), k=-1)
print (z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19.创建一个8X8的矩阵,并且设置成棋盘样子

In [47]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print (z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. 考虑一个(6,7,8)形状的数组,其第100个元素的索引(x,y,z)是什么?

In [2]:
import numpy as np
print (np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


### 21.用tile函数创建一个8x8的棋盘样式矩阵

In [4]:
z = np.tile(np.array([[1, 1],[1, 1]]), (4, 4))
z

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

### 22. 对一个5x5的随机矩阵做归一化 

In [6]:
z = np.random.random((5, 5))
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[0.293372  , 0.78170959, 0.83535066, 0.67256972, 0.89373352],
       [0.4833814 , 0.97915367, 0.85508976, 0.72903597, 0.8192265 ],
       [0.89695501, 0.60975538, 0.51389536, 0.16209564, 0.        ],
       [0.17984446, 0.93391369, 0.17429041, 1.        , 0.22764467],
       [0.46923326, 0.00915632, 0.92792367, 0.32076378, 0.44467791]])

### 23.创建一个将颜色描述成为(RGBA)四个无符号字节的自定义dtype?

In [8]:
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24.  一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [11]:
z = np.dot(np.random.random((5, 3)), np.random.random((3, 2)))
z

array([[0.22490313, 0.23660535],
       [0.16924961, 0.08258876],
       [0.60809524, 0.65655527],
       [0.45234949, 0.60646208],
       [0.88662979, 0.68887627]])

### 25.给定一个一维数组,对其在3到8之间的所有元素取反 

In [28]:
z = np.arange(11)
z[(z>3) & (z <= 8)]*=-1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

### 26.下面脚本运行的结果

In [ ]:
#------ 普通的sum和np.sum ----------
print (sum(range(5), -1))
import numpy as np
print (np.sum(range(5), -1))

### 27.考虑一个整数向量z,下列表达合法的是哪一个?

In [42]:
z = np.arange(5)
z ** z
2 << z >> 2
z < -z
1j*z
z/1/1
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28.下列表达式的结果分别是什么?

In [45]:
print (np.array(0)/np.array(0))
print (np.array(0)//np.array(0))
print (np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\wd\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\wd\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### 29.如何从零位对浮点数组做舍入?

In [47]:
z = np.random.randn(10)
print (np.copysign(np.ceil(np.abs(z)), z))

[ 1. -1.  1.  2. -1. -1. -3. -2. -2. -3.]


### 30.如何找到两个数组中的共同元素？ 

In [49]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
print (np.intersect1d(z1, z2))

[1 4 6 7]


### 31.如何忽略所有的numpy的警告

In [51]:
defaults = np.seterr(all="ignore")
z = np.ones(1)/0

### 32.下面的表达式是正确的吗? 

In [53]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33.如何得到昨天,今天和明天的日期

In [66]:
import datetime
from datetime import datetime
from datetime import timedelta
#from datetime import datetime
print (datetime.now().strftime("%Y%m%d"))
print ((datetime.now() - timedelta(days=1)).strftime("%Y%m%d"))
print ((datetime.now() + timedelta(days=1)).strftime("%Y%m%d"))

#------------ 如果是使用numpy ---------------
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print (yesterday, today, tomorrow)

20190622
20190621
20190623
2019-06-21 2019-06-22 2019-06-23


### 34. 如何得到所有与2016年7月对应的日期

In [70]:
#import pandas as pd
#pd.date_range('2016-07', '2016-08', freq='D')
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print (z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35.如何直接在位计算(A+B)\*(-A/2)(不建立副本)

In [74]:
a = np.ones(3)*1
b = np.ones(3)*2
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
print (a)

[-1.5 -1.5 -1.5]


### 36.用五种不同的方法去提取一个随机数组的整数部分

In [75]:
z1 = np.random.uniform(0, 10, 10)
print (z1 - z1%1)
print (np.floor(z1))
print (np.ceil(z1)-1)
print (z1.astype(int))
print (np.trunc(z1))

[1. 6. 1. 1. 2. 2. 5. 8. 2. 5.]
[1. 6. 1. 1. 2. 2. 5. 8. 2. 5.]
[1. 6. 1. 1. 2. 2. 5. 8. 2. 5.]
[1 6 1 1 2 2 5 8 2 5]
[1. 6. 1. 1. 2. 2. 5. 8. 2. 5.]


### 37. 创建一个5x5的矩阵,其中每行的数值范围从0到4?

In [77]:
z = np.zeros((5, 5))
z += np.arange(5)
print (z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38.通过考虑一个可生成10个整数的函数,来构建一个数组?

In [79]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(), dtype=float, count=-1)
print (z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 

In [82]:
z = np.linspace(0, 1, 11, endpoint=False)[1:]
print (z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40.创建一个长度为10的随机向量,并将其排序?

In [84]:
z = np.random.random(10)
z.sort()
print (z)

[0.01401962 0.02875116 0.25644721 0.27565284 0.39161509 0.56629878
 0.58575249 0.59274886 0.74995888 0.74997378]


### 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [86]:
z = np.arange(10)
np.add.reduce(z)

45

### 42.对于两个随机数组A和B,检查它们是否相等？

In [88]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
equal = np.array_equal(a, b)
print (equal)

False


### 43.创建一个只读数组(read-only)?

In [90]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

### 44.将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [92]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y, x)
print (r)
print (t)

[0.54790908 0.85975446 0.63383593 1.05544252 1.0690693  0.65811713
 1.05296989 1.13664113 0.92809703 0.81895575]
[0.12828178 1.42156981 0.67813026 0.41322385 1.10512892 0.12901701
 0.45764103 0.85290901 0.80399589 0.26030202]


### 45.创建一个长度为10的向量，并将向量中最大值替换为1

In [94]:
z = np.random.random(10)
z[z.argmax()]= 0
print (z)

[0.7331995  0.         0.30629086 0.6697862  0.52748003 0.26426854
 0.19062991 0.22530777 0.05388298 0.22751912]


### 46.创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域?

In [96]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5),
                             np.linspace(0, 1, 5))
print (z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47.给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [98]:
x = np.arange(8)
y = x + 0.5
c = 1.0/np.subtract.outer(x, y)
print (np.linalg.det(c))

3638.163637117973


### 48.打印每个numpy标量类型的最小值和最大值？

In [100]:
for dtype in [np.int8, np.int32, np.int64]:
    print (np.iinfo(dtype).min)
    print (np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print (np.finfo(dtype).min)
    print (np.finfo(dtype).max)
    print (np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49.如何打印一个数组中的所有数值?

In [104]:
np.set_printoptions()
z = np.zeros((16, 16))
print (z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 50.给定标量时，如何找到数组中最接近标量的值？

In [106]:
z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(z-v)).argmin()
print (z[index])

71


### 51.创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [108]:
 Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
 print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


### 52.对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

In [111]:
z = np.random.random((100, 2))
x, y = np.atleast_2d(z[:, 0], z[:, 1])
d = np.sqrt((x-x.T)**2 + (y - y.T)**2)
print (d)

[[0.         0.60922452 0.19179783 ... 0.58416535 0.90574669 0.32310778]
 [0.60922452 0.         0.51404055 ... 0.35367363 0.30349617 0.29365618]
 [0.19179783 0.51404055 0.         ... 0.60346015 0.78771185 0.22647832]
 ...
 [0.58416535 0.35367363 0.60346015 ... 0.         0.5863167  0.41146918]
 [0.90574669 0.30349617 0.78771185 ... 0.5863167  0.         0.58360461]
 [0.32310778 0.29365618 0.22647832 ... 0.41146918 0.58360461 0.        ]]


### 53.如何将32位的浮点数(float)转换为对应的整数(integer)?

In [113]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print (z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 54.如何读取以下文件?

In [119]:
from io import StringIO
s = StringIO('1, 2, 3, 4, 5,\
6,  ,  , 7, 8,\
 ,  , 9,10,11')
data = np.genfromtxt(s, delimiter=',')
data

array([ 1.,  2.,  3.,  4.,  5.,  6., nan, nan,  7.,  8., nan, nan,  9.,
       10., 11.])

### 55.对于numpy数组，enumerate的等价操作是什么？

In [121]:
z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(z):
    print (index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56.生成一个通用的二维Gaussian-like数组

In [123]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/(2.0*sigma**2)))
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57.对一个二维数组，如何在其内部随机放置p个元素?

In [125]:
n = 10
p = 3
z = np.zeros((n, n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print (z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]


### 58.减去一个矩阵中的每一行的平均值

In [127]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print (y)

[[ 0.02312048  0.21305223  0.40296488  0.13894884 -0.48279984 -0.04861342
  -0.06887694 -0.36769515 -0.0850094   0.27490832]
 [-0.01423579  0.16919064 -0.36547737  0.14843317  0.08031741  0.51882491
  -0.15054414 -0.36390961 -0.33888657  0.31628735]
 [ 0.13541975  0.13677348  0.36164443  0.01832611 -0.04142444 -0.30876532
  -0.18873324  0.3114785  -0.46501024  0.04029097]
 [-0.39846016  0.47419689 -0.09099618  0.16866576  0.16552555  0.096927
   0.09095178 -0.30436963 -0.27377779  0.07133677]
 [ 0.03895306  0.15226721  0.4084355  -0.22291873 -0.22686615  0.3796636
  -0.18025312 -0.19420935  0.11885471 -0.27392674]]


### 59.如何通过第n列对一个数组进行排序?

In [129]:
z = np.random.randint(0, 10, (3, 3))
print (z)
print (z[z[:, 1].argsort()])

[[7 7 7]
 [5 2 4]
 [0 0 7]]
[[0 0 7]
 [5 2 4]
 [7 7 7]]


### 60.如何检查一个二维数组是否有空列？

In [131]:
z = np.random.randint(0, 3, (3, 10))
print ((~z.any(axis=0)).any())

False


### 61.从数组中的给定值中找出最近的值  

In [134]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print (m)

0.5029050757570738


### 62.如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组? 

In [136]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 63.创建一个具有name属性的数组类

In [138]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
z = NamedArray(np.arange(10), "range_10")
print (z.name)

range_10


### 64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)?

In [140]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
z += np.bincount(i, minlength=len(z))
print (z)

[4. 1. 2. 4. 5. 2. 3. 2. 4. 3.]


### 65.根据索引列表(I)，如何将向量(X)的元素累加到数组(F)? 

In [142]:
x = [1, 2, 3, 4, 5, 6]
i = [1, 3, 9, 3, 4, 1]
f = np.bincount(i, x)
print (f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### 66.考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量

In [144]:
 w,h = 16,16
 I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
 #Note that we should compute 256*256 first. 
 #Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
 F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
 n = len(np.unique(F))
 print (n)

8


### 67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？ 

In [146]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
mysum = A.sum(axis=(-2, -1))
print (mysum)

[[54 43 60 49]
 [57 42 59 67]
 [60 56 37 49]]


### 68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [148]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums/D_counts
print (D_means)

[0.37013684 0.54409314 0.49415909 0.37031053 0.50829727 0.34989604
 0.41744162 0.53268426 0.45840588 0.70989058]


### 69. 如何获得点积dot product的对角线？

In [149]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
np.sum(A * B.T, axis=1)

array([0.83282198, 0.74891386, 0.35774325, 0.65112362, 0.92946907])

### 70.考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？

In [151]:
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### 71.考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？ 

In [153]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print (A * B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### 72.  如何对一个数组中任意两行做交换? 

In [157]:
import numpy as np
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 73.考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [158]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print (G)

[( 2, 23) ( 2, 39) ( 2, 87) ( 2, 90) ( 5, 22) ( 5, 23) ( 5, 60) ( 5, 70)
 ( 8, 13) ( 8, 76) (11, 29) (11, 80) (13, 76) (22, 60) (23, 70) (23, 87)
 (29, 80) (31, 38) (31, 82) (38, 82) (39, 90) (43, 64) (43, 91) (52, 74)
 (52, 88) (63, 75) (63, 95) (64, 91) (74, 88) (75, 95)]


### 74.给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

In [160]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


### 75. 如何通过滑动窗口计算一个数组的平均数?

In [162]:
def moving_average(a, n = 3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:]/n
z = np.arange(20)
print (moving_average(z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### 76.Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [165]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z = rolling(np.arange(10), 3)
print (z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### 77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？

In [167]:
z = np.random.randint(0, 2, 100)
np.negative(z, out=z)

array([-1, -1, -1, -1,  0,  0,  0,  0, -1, -1, -1,  0,  0,  0, -1, -1,  0,
       -1, -1, -1, -1, -1, -1, -1,  0,  0, -1, -1,  0, -1,  0,  0,  0,  0,
       -1, -1, -1, -1, -1, -1,  0,  0, -1,  0,  0, -1,  0,  0,  0, -1, -1,
       -1,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1, -1, -1, -1,
        0,  0, -1,  0,  0, -1,  0, -1,  0, -1, -1, -1,  0, -1,  0, -1,  0,
       -1, -1,  0, -1, -1,  0,  0,  0,  0,  0, -1,  0,  0, -1,  0])

### 78.考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？

In [171]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print (distance(P0, P1, p))

[2.99388387 6.1292126  6.40807323 1.68217059 3.65877054 7.87804216
 7.8560661  1.62522062 4.17557557 9.75545815]


### 79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？

In [173]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p  = np.random.uniform(-10, 10, (10, 2))
print (np.array([distance(P0, P1, p_i) for p_i in p]))

[[ 6.57473038  3.36344841  3.59481072  1.83561736 11.89483886  3.45682078
   4.90921417  4.55510584  6.78582378  1.24372269]
 [ 4.63993444  1.38517267  5.97937182  2.68112174 13.63122099  5.19420049
   2.35321247  2.77283669  4.77693459  3.64751767]
 [ 0.79734364  4.11801939 10.73039536  3.04484063 16.33699975 10.3137392
   3.62138254  0.06340824  0.77162122  9.65356653]
 [ 4.11445544  7.28503392  7.03373388  3.53857368 10.63612409 14.23865487
   3.17968841  5.55276183  3.82878211 10.78393765]
 [10.2573893   7.0127225   3.08099628  4.37949891 13.07642555  0.33931501
   7.28025747  3.46397974 10.40943487  1.78531528]
 [ 0.4507698   2.5947957   0.63028732  6.33532055  5.67295887 10.23368437
   3.33274685 10.62359695  0.94989225  4.81358743]
 [ 3.37878845  6.48866067  4.59621815  5.43968438  8.26947492 13.76412688
   1.25925147  7.93567195  2.98884603  9.28182256]
 [10.08158404  6.7994445   4.45936202  5.65504323 14.52914339  0.32265362
   6.32817315  2.00799288 10.16915027  1.12059184]
 

### 80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [175]:
 Z = np.random.randint(0,10,(10,10))
 shape = (5,5)
 fill  = 0
 position = (1,1)

 R = np.ones(shape, dtype=Z.dtype)*fill
 P  = np.array(list(position)).astype(int)
 Rs = np.array(list(R.shape)).astype(int)
 Zs = np.array(list(Z.shape)).astype(int)

 R_start = np.zeros((len(shape),)).astype(int)
 R_stop  = np.array(list(shape)).astype(int)
 Z_start = (P-Rs//2)
 Z_stop  = (P+Rs//2)+Rs%2

 R_start = (R_start - np.minimum(Z_start,0)).tolist()
 Z_start = (np.maximum(Z_start,0)).tolist()
 R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
 Z_stop = (np.minimum(Z_stop,Zs)).tolist()

 r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
 z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
 R[r] = Z[z]
 print (Z)
 print (R)

[[1 0 4 0 5 1 5 5 7 6]
 [2 0 1 6 0 0 1 0 9 2]
 [9 0 7 0 8 0 5 5 7 7]
 [0 2 9 1 8 8 6 5 5 1]
 [9 4 5 0 3 8 2 5 4 0]
 [0 7 3 3 9 7 1 3 1 2]
 [6 1 9 3 5 4 4 6 4 6]
 [8 0 2 4 3 8 5 8 1 1]
 [8 7 2 4 0 2 2 5 4 9]
 [0 7 0 9 1 9 7 7 4 1]]
[[0 0 0 0 0]
 [0 1 0 4 0]
 [0 2 0 1 6]
 [0 9 0 7 0]
 [0 0 2 9 1]]


C:\Users\wd\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


### 81.考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 

In [177]:
z = np.arange(1, 15, dtype=np.uint32)
r = stride_tricks.as_strided(z, (11, 4), (4, 4))
print (r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. 计算一个矩阵的秩

In [178]:
z = np.random.uniform(0, 1, (10, 10))
u, s, v = np.linalg.svd(z)
rank = np.sum(s > 1e-10)
print (rank)

10


### 83.如何找到一个数组中出现频率最高的值？

In [179]:
z = np.random.randint(0, 10, 50)
print (np.bincount(z).argmax())

4


### 84.从一个10x10的矩阵中提取出连续的3x3区块

In [182]:
z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (z.shape[0]-3)
j = 1 + (z.shape[1]-3)
c = stride_tricks.as_strided(z, shape=(i, j, n, n), strides=z.strides + z.strides)
print (c)

[[[[1 2 0]
   [1 0 0]
   [4 4 3]]

  [[2 0 2]
   [0 0 1]
   [4 3 4]]

  [[0 2 0]
   [0 1 2]
   [3 4 3]]

  [[2 0 2]
   [1 2 2]
   [4 3 0]]

  [[0 2 0]
   [2 2 0]
   [3 0 3]]

  [[2 0 2]
   [2 0 2]
   [0 3 4]]

  [[0 2 1]
   [0 2 2]
   [3 4 0]]

  [[2 1 2]
   [2 2 3]
   [4 0 1]]]


 [[[1 0 0]
   [4 4 3]
   [2 4 2]]

  [[0 0 1]
   [4 3 4]
   [4 2 0]]

  [[0 1 2]
   [3 4 3]
   [2 0 2]]

  [[1 2 2]
   [4 3 0]
   [0 2 3]]

  [[2 2 0]
   [3 0 3]
   [2 3 2]]

  [[2 0 2]
   [0 3 4]
   [3 2 0]]

  [[0 2 2]
   [3 4 0]
   [2 0 1]]

  [[2 2 3]
   [4 0 1]
   [0 1 4]]]


 [[[4 4 3]
   [2 4 2]
   [1 3 0]]

  [[4 3 4]
   [4 2 0]
   [3 0 1]]

  [[3 4 3]
   [2 0 2]
   [0 1 4]]

  [[4 3 0]
   [0 2 3]
   [1 4 4]]

  [[3 0 3]
   [2 3 2]
   [4 4 4]]

  [[0 3 4]
   [3 2 0]
   [4 4 3]]

  [[3 4 0]
   [2 0 1]
   [4 3 4]]

  [[4 0 1]
   [0 1 4]
   [3 4 3]]]


 [[[2 4 2]
   [1 3 0]
   [1 4 0]]

  [[4 2 0]
   [3 0 1]
   [4 0 3]]

  [[2 0 2]
   [0 1 4]
   [0 3 0]]

  [[0 2 3]
   [1 4 4]
   [3 0 4]]

  [[2 3 2]
   

### 85.创建一个满足 Z[i,j] == Z[j,i]的子类

In [183]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

def symetric(z):
    return np.asarray(z+z.T - np.diag(z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
print (S)

[[ 3 17 10  3  6]
 [17  2 12  9  3]
 [10 12  8 42 17]
 [ 3  9 42  9 17]
 [ 6  3 17 17  3]]


### 86.考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？

In [184]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


### 87.对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)?

In [185]:
 Z = np.ones((16,16))
 k = 4
 S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                        np.arange(0, Z.shape[1], k), axis=1)
 print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88.如何利用numpy数组实现Game of Life?

In [186]:
 def iterate(Z):
     # Count neighbours
     N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
          Z[1:-1,0:-2]                + Z[1:-1,2:] +
          Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

#     # Apply rules
     birth = (N==3) & (Z[1:-1,1:-1]==0)
     survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
     Z[...] = 0
     Z[1:-1,1:-1][birth | survive] = 1
     return Z

 Z = np.random.randint(0,2,(50,50))
 for i in range(100): Z = iterate(Z)
 print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### 89.如何找到一个数组的第n个最大值?

In [188]:
Z = np.arange(1000)
#--- 打乱顺序 --------
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z, n)[:n]])

[997 998 999 996 995]


### 90.给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)

In [189]:
 def cartesian(arrays):
     arrays = [np.asarray(a) for a in arrays]
     shape = (len(x) for x in arrays)

     ix = np.indices(shape, dtype=int)
     ix = ix.reshape(len(arrays), -1).T

     for n, arr in enumerate(arrays):
         ix[:, n] = arrays[n][ix[:, n]]

     return ix

 print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### 91.如何从一个正常数组创建记录数组(record array)? 

In [190]:
 Z = np.array([("Hello", 2.5, 3),
               ("World", 3.6, 2)])
 R = np.core.records.fromarrays(Z.T, 
                                names='col1, col2, col3',
                                formats = 'S8, f8, i8')
 print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### 92.考虑一个大向量Z, 用三种不同的方法计算它的立方

In [191]:
x = np.random.rand()
np.power(x, 3)
x * x * x
np.einsum('i, i, i->i', x, x, x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

### 93.考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

In [193]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 2 4]


### 94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) 

In [194]:
z = np.random.randint(0, 5, (10, 3))
print (z)
E = np.all(z[:, 1:] == z[:, :-1], axis=1)
U = Z[~E]
print (U)

[[4 0 1]
 [2 3 2]
 [3 3 1]
 [2 3 0]
 [3 0 2]
 [4 2 1]
 [3 3 3]
 [4 1 0]
 [1 1 0]
 [3 1 2]]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 10

### 95.将一个整数向量转换为matrix binary的表现形式

In [195]:
print (np.unpackbits(I[:, np.newaxis], axis=1))

[[[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 1 1]
   [0 1 1]
   ...
   [0 1 0]
   [1 1 0]
   [0 0 1]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 1]
   [0 1 0]
   [1 0 0]
   ...
   [1 0 0]
   [0 0 1]
   [0 1 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0

### 96.给定一个二维数组，如何提取出唯一的(unique)行?

In [196]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]


### 97.考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

In [197]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)
print ('sum')
print (np.einsum('i->', A))

sum
5.675428551843291


### 98.考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)? 

In [198]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

### 99.Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [199]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                 [2.0, 0.0, 1.0, 1.0],
                 [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


### 100.对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。

In [200]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[0.05399473 0.41274363]
